REMOTE_USER="user"
REMOTE_HOST="192.168.0.8"
REMOTE_DIR="/home/user/Desktop/Inzheneria"
ARCHIVE_NAME="backup_$(date +%Y%m%d).tar.gz"
LOCAL_DIR="e:/example"
echo "Архивирование директории на удаленном сервере..."
ssh "$REMOTE_USER@$REMOTE_HOST" "tar -czf /tmp/$ARCHIVE_NAME -C $(dirname "$REMOTE_DIR") $(basename "$REMOTE_DIR")"
mkdir -p "$LOCAL_DIR"
scp "$REMOTE_USER@$REMOTE_HOST:/tmp/$ARCHIVE_NAME" "$LOCAL_DIR/"
echo "Удаление временного архива на удаленном сервере..."
ssh "$REMOTE_USER@$REMOTE_HOST" "rm /tmp/$ARCHIVE_NAME"
echo "Распаковка архива на локальной машине..."
tar -xzf "$LOCAL_DIR/$ARCHIVE_NAME" -C "$LOCAL_DIR"
echo "Операция завершена. Архив и содержимое находятся в директории: $LOCAL_DIR"