REMOTE_SERVER="user@192.168.0.8"
REMOTE_DIR="/home/user/Desktop/Inzheneria"
ARCHIVE_NAME="backup_$(date +%F).tar.gz"
LOCAL_BACKUP_DIR="e:/example"
LOCAL_DIR="e:/example"
REMOTE_EXTRACT_DIR="/home/user/Desktop/Inzheneria/extracted"
REMOTE_ARCHIVE="/tmp/$ARCHIVE_NAME"
ssh $REMOTE_SERVER "tar -czf /tmp/$ARCHIVE_NAME -C $REMOTE_DIR ."
ssh $REMOTE_SERVER "mkdir -p $REMOTE_EXTRACT_DIR && tar -xzf $REMOTE_ARCHIVE -C $REMOTE_EXTRACT_DIR"